version: "3"

services:
  # Setup Meilisearch instance
  meilisearch:
    # Original REPO set specific meilisearch tag for some reason
    container_name: meilisearch
    hostname: meilisearch
    image: getmeili/meilisearch:v0.29
    environment:
      - MEILI_MASTER_KEY=REDACTED
      - MEILI_ENV=production
      - TZ=America/Chicago
    networks:
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true
      traefik.enable: true
      traefik.http.routers.meilisearch-http.entrypoints: web
      traefik.http.routers.meilisearch-http.middlewares: globalHeaders@file,redirect-to-https,gzip
      traefik.http.routers.meilisearch-http.rule: Host(`meilisearch.domain.tld`)
      traefik.http.routers.meilisearch-http.service: meilisearch
      traefik.http.routers.meilisearch.entrypoints: websecure
      traefik.http.routers.meilisearch.middlewares: globalHeaders@file,secureHeaders@file,authelia@docker
      traefik.http.routers.meilisearch.rule: Host(`meilisearch.domain.tld`)
      traefik.http.routers.meilisearch.service: meilisearch
      traefik.http.routers.meilisearch.tls.certresolver: cfdns
      traefik.http.routers.meilisearch.tls.options: securetls@file
      traefik.http.services.meilisearch.loadbalancer.server.port: 7700
    restart: unless-stopped
    ports:
      - 7700:7700
    volumes:
      - ba-meilidata:/meili_data
      - /etc/localtime:/etc/localtime:ro

  # Redis for session and file cache
  redis_salt-rim:
    container_name: redis_salt-rim
    hostname: redis_salt-rim
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true
    restart: unless-stopped

  # Bar Assistant API
  bar-assistant:
    container_name: bar-assistant
    hostname: bar-assistant
    image: kmikus12/bar-assistant-server
    depends_on:
      - meilisearch
      - redis_salt-rim
    environment:
      - APP_URL=https://bar-assistant.domain.tld
      - MEILISEARCH_KEY=REDACTED
      - MEILISEARCH_HOST=http://meilisearch:7700
      - REDIS_HOST=redis_salt-rim
      - TZ=America/Chicago
    networks:
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true
      traefik.enable: true
      traefik.http.routers.bar-assistant-http.entrypoints: web
      traefik.http.routers.bar-assistant-http.middlewares: globalHeaders@file,redirect-to-https,gzip
      traefik.http.routers.bar-assistant-http.rule: Host(`bar-assistant.domain.tld`)
      traefik.http.routers.bar-assistant-http.service: bar-assistant
      traefik.http.routers.bar-assistant.entrypoints: websecure
      traefik.http.routers.bar-assistant.middlewares: globalHeaders@file,secureHeaders@file,authelia@docker
      traefik.http.routers.bar-assistant.rule: Host(`bar-assistant.domain.tld`)
      traefik.http.routers.bar-assistant.service: bar-assistant
      traefik.http.routers.bar-assistant.tls.certresolver: cfdns
      traefik.http.routers.bar-assistant.tls.options: securetls@file
      traefik.http.services.bar-assistant.loadbalancer.server.port: 8000
    restart: unless-stopped
    volumes:
      - ba-storage:/var/www/cocktails/storage
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8000:80

  # Bar Assistant Web Client
  salt-rim:
    container_name: salt-rim
    hostname: salt-rim
    image: kmikus12/salt-rim
    restart: unless-stopped
    depends_on:
      - meilisearch
      - bar-assistant
    environment:
      - API_URL=http://bar-assistant:8000 # This guy 
      - TZ=America/Chicago
    networks:
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true
      traefik.enable: true
      traefik.http.routers.salt-rim-http.entrypoints: web
      traefik.http.routers.salt-rim-http.middlewares: globalHeaders@file,redirect-to-https,gzip
      traefik.http.routers.salt-rim-http.rule: Host(`salt-rim.domain.tld`)
      traefik.http.routers.salt-rim-http.service: salt-rim
      traefik.http.routers.salt-rim.entrypoints: websecure
      traefik.http.routers.salt-rim.middlewares: globalHeaders@file,secureHeaders@file,authelia@docker
      traefik.http.routers.salt-rim.rule: Host(`salt-rim.domain.tld`)
      traefik.http.routers.salt-rim.service: salt-rim
      traefik.http.routers.salt-rim.tls.certresolver: cfdns
      traefik.http.routers.salt-rim.tls.options: securetls@file
      traefik.http.services.salt-rim.loadbalancer.server.port: 8080
    ports: 
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro

volumes:
  ba-meilidata:
  ba-storage:

networks:
  saltbox:
    external: true
